# Generated by Django 5.2.8 on 2025-12-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='followers',
            name='user',
            field=models.CharField(default='', max_length=100),
        ),
    ]
