# Generated by Django 5.2.8 on 2025-12-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0006_remove_likepost_post_id_remove_likepost_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likepost',
            name='post',
        ),
        migrations.RemoveField(
            model_name='likepost',
            name='user',
        ),
        migrations.AddField(
            model_name='likepost',
            name='post_id',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='likepost',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
